//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleActivity.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleActivity.Properties.Resources - Copy", typeof(Resources___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma separated list of AppSettings to output..
        /// </summary>
        internal static string AppSettingsSettings_AppSettingsToOutput_Description {
            get {
                return ResourceManager.GetString("AppSettingsSettings.AppSettingsToOutput.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppSettings.
        /// </summary>
        internal static string AppSettingsSettings_AppSettingsToOutput_Name {
            get {
                return ResourceManager.GetString("AppSettingsSettings.AppSettingsToOutput.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom value where to output AppSettings..
        /// </summary>
        internal static string AppSettingsSettings_OutputCustomValue_Description {
            get {
                return ResourceManager.GetString("AppSettingsSettings.OutputCustomValue.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Custom Value.
        /// </summary>
        internal static string AppSettingsSettings_OutputCustomValue_Name {
            get {
                return ResourceManager.GetString("AppSettingsSettings.OutputCustomValue.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtering custom value name..
        /// </summary>
        internal static string CommonSettings_FilteringCustomValueName_Description {
            get {
                return ResourceManager.GetString("CommonSettings.FilteringCustomValueName.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtering Custom Value Name.
        /// </summary>
        internal static string CommonSettings_FilteringCustomValueName_Name {
            get {
                return ResourceManager.GetString("CommonSettings.FilteringCustomValueName.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing custom value name..
        /// </summary>
        internal static string CommonSettings_RoutingCustomValueName_Description {
            get {
                return ResourceManager.GetString("CommonSettings.RoutingCustomValueName.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing Custom Value Name.
        /// </summary>
        internal static string CommonSettings_RoutingCustomValueName_Name {
            get {
                return ResourceManager.GetString("CommonSettings.RoutingCustomValueName.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just a path to a file.
        /// </summary>
        internal static string ConfigurationValidationSettings_FilePath_Description {
            get {
                return ResourceManager.GetString("ConfigurationValidationSettings.FilePath.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path.
        /// </summary>
        internal static string ConfigurationValidationSettings_FilePath_Name {
            get {
                return ResourceManager.GetString("ConfigurationValidationSettings.FilePath.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If IfThisIsTrue is true, then ThisMustNotBeEmpty must not be empty.
        /// </summary>
        internal static string ConfigurationValidationSettings_IfThisIsTrue_Description {
            get {
                return ResourceManager.GetString("ConfigurationValidationSettings.IfThisIsTrue.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just a Group.
        /// </summary>
        internal static string ConfigurationValidationSettings_IfThisIsTrue_GroupName {
            get {
                return ResourceManager.GetString("ConfigurationValidationSettings.IfThisIsTrue.GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If This Is True.
        /// </summary>
        internal static string ConfigurationValidationSettings_IfThisIsTrue_Name {
            get {
                return ResourceManager.GetString("ConfigurationValidationSettings.IfThisIsTrue.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Date Must Be In The Future.
        /// </summary>
        internal static string ConfigurationValidationSettings_ThisMustBeInTheFuture_Description {
            get {
                return ResourceManager.GetString("ConfigurationValidationSettings.ThisMustBeInTheFuture.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just another Group.
        /// </summary>
        internal static string ConfigurationValidationSettings_ThisMustBeInTheFuture_GroupName {
            get {
                return ResourceManager.GetString("ConfigurationValidationSettings.ThisMustBeInTheFuture.GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Must Be In The Future.
        /// </summary>
        internal static string ConfigurationValidationSettings_ThisMustBeInTheFuture_Name {
            get {
                return ResourceManager.GetString("ConfigurationValidationSettings.ThisMustBeInTheFuture.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Date Must Be In The Past.
        /// </summary>
        internal static string ConfigurationValidationSettings_ThisMustBeInThePast_Description {
            get {
                return ResourceManager.GetString("ConfigurationValidationSettings.ThisMustBeInThePast.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just another Group.
        /// </summary>
        internal static string ConfigurationValidationSettings_ThisMustBeInThePast_GroupName {
            get {
                return ResourceManager.GetString("ConfigurationValidationSettings.ThisMustBeInThePast.GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Must Be In The Past.
        /// </summary>
        internal static string ConfigurationValidationSettings_ThisMustBeInThePast_Name {
            get {
                return ResourceManager.GetString("ConfigurationValidationSettings.ThisMustBeInThePast.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If IfThisIsTrue is true, then ThisMustNotBeEmpty must not be empty.
        /// </summary>
        internal static string ConfigurationValidationSettings_ThisMustNotBeEmpty_Description {
            get {
                return ResourceManager.GetString("ConfigurationValidationSettings.ThisMustNotBeEmpty.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just a Group.
        /// </summary>
        internal static string ConfigurationValidationSettings_ThisMustNotBeEmpty_GroupName {
            get {
                return ResourceManager.GetString("ConfigurationValidationSettings.ThisMustNotBeEmpty.GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Must Not Be Empty.
        /// </summary>
        internal static string ConfigurationValidationSettings_ThisMustNotBeEmpty_Name {
            get {
                return ResourceManager.GetString("ConfigurationValidationSettings.ThisMustNotBeEmpty.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing and Filtering Settings.
        /// </summary>
        internal static string ExportSettings_Common_Name {
            get {
                return ResourceManager.GetString("ExportSettings.Common.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps media to be exported to the extensions of exported files.
        /// </summary>
        internal static string ExportSettings_ExportMediaMappings_Description {
            get {
                return ResourceManager.GetString("ExportSettings.ExportMediaMappings.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Mapping.
        /// </summary>
        internal static string ExportSettings_ExportMediaMappings_Name {
            get {
                return ResourceManager.GetString("ExportSettings.ExportMediaMappings.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to where the files are going to be exported.
        /// </summary>
        internal static string ExportSettings_ExportPath_Description {
            get {
                return ResourceManager.GetString("ExportSettings.ExportPath.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Path.
        /// </summary>
        internal static string ExportSettings_ExportPath_Name {
            get {
                return ResourceManager.GetString("ExportSettings.ExportPath.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the files are put in the same (export) folder.
        /// </summary>
        internal static string ExportSettings_FlatExport_Description {
            get {
                return ResourceManager.GetString("ExportSettings.FlatExport.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat Export.
        /// </summary>
        internal static string ExportSettings_FlatExport_Name {
            get {
                return ResourceManager.GetString("ExportSettings.FlatExport.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common settings..
        /// </summary>
        internal static string ImportSettings_Common_Description {
            get {
                return ResourceManager.GetString("ImportSettings.Common.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Settings.
        /// </summary>
        internal static string ImportSettings_Common_Name {
            get {
                return ResourceManager.GetString("ImportSettings.Common.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the document type.
        /// </summary>
        internal static string ImportSettings_DocumentType_Description {
            get {
                return ResourceManager.GetString("ImportSettings.DocumentType.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        internal static string ImportSettings_DocumentType_Name {
            get {
                return ResourceManager.GetString("ImportSettings.DocumentType.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import path..
        /// </summary>
        internal static string ImportSettings_ImportPath_Description {
            get {
                return ResourceManager.GetString("ImportSettings.ImportPath.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Path.
        /// </summary>
        internal static string ImportSettings_ImportPath_Name {
            get {
                return ResourceManager.GetString("ImportSettings.ImportPath.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jpeg filter..
        /// </summary>
        internal static string ImportSettings_JpegFilter_Description {
            get {
                return ResourceManager.GetString("ImportSettings.JpegFilter.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jpeg Filter.
        /// </summary>
        internal static string ImportSettings_JpegFilter_Name {
            get {
                return ResourceManager.GetString("ImportSettings.JpegFilter.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiff filter..
        /// </summary>
        internal static string ImportSettings_TiffFilter_Description {
            get {
                return ResourceManager.GetString("ImportSettings.TiffFilter.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiff Filter.
        /// </summary>
        internal static string ImportSettings_TiffFilter_Name {
            get {
                return ResourceManager.GetString("ImportSettings.TiffFilter.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of days the work item must be in the overdue SLA status in order to be counted for notification..
        /// </summary>
        internal static string OverdueAgentSettings_DaysOverdue_Description {
            get {
                return ResourceManager.GetString("OverdueAgentSettings.DaysOverdue.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One day or more.
        /// </summary>
        internal static string OverdueAgentSettings_DaysOverdue_Enum_Val1 {
            get {
                return ResourceManager.GetString("OverdueAgentSettings.DaysOverdue.Enum.Val1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Days or more.
        /// </summary>
        internal static string OverdueAgentSettings_DaysOverdue_Enum_Val2 {
            get {
                return ResourceManager.GetString("OverdueAgentSettings.DaysOverdue.Enum.Val2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three days or more.
        /// </summary>
        internal static string OverdueAgentSettings_DaysOverdue_Enum_Val3 {
            get {
                return ResourceManager.GetString("OverdueAgentSettings.DaysOverdue.Enum.Val3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five days or more.
        /// </summary>
        internal static string OverdueAgentSettings_DaysOverdue_Enum_Val5 {
            get {
                return ResourceManager.GetString("OverdueAgentSettings.DaysOverdue.Enum.Val5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A week or more.
        /// </summary>
        internal static string OverdueAgentSettings_DaysOverdue_Enum_Val7 {
            get {
                return ResourceManager.GetString("OverdueAgentSettings.DaysOverdue.Enum.Val7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02 - Notification.
        /// </summary>
        internal static string OverdueAgentSettings_DaysOverdue_GroupName {
            get {
                return ResourceManager.GetString("OverdueAgentSettings.DaysOverdue.GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Overdue.
        /// </summary>
        internal static string OverdueAgentSettings_DaysOverdue_Name {
            get {
                return ResourceManager.GetString("OverdueAgentSettings.DaysOverdue.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this option is selected, the agent will count also work items that are in the CloseTo status..
        /// </summary>
        internal static string OverdueAgentSettings_IncludeCloseTo_Description {
            get {
                return ResourceManager.GetString("OverdueAgentSettings.IncludeCloseTo.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02 - Notification.
        /// </summary>
        internal static string OverdueAgentSettings_IncludeCloseTo_GroupName {
            get {
                return ResourceManager.GetString("OverdueAgentSettings.IncludeCloseTo.GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Including CloseTo.
        /// </summary>
        internal static string OverdueAgentSettings_IncludeCloseTo_Name {
            get {
                return ResourceManager.GetString("OverdueAgentSettings.IncludeCloseTo.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explains what this system agent does..
        /// </summary>
        internal static string OverdueAgentSettings_Readme_Description {
            get {
                return ResourceManager.GetString("OverdueAgentSettings.Readme.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01 - Description.
        /// </summary>
        internal static string OverdueAgentSettings_Readme_GroupName {
            get {
                return ResourceManager.GetString("OverdueAgentSettings.Readme.GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadMe.
        /// </summary>
        internal static string OverdueAgentSettings_Readme_Name {
            get {
                return ResourceManager.GetString("OverdueAgentSettings.Readme.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This system agent ticks as configured on the process settings tab. /n With every tick it counts the number of work items that have the SLA status in Overdue (and alternatively in Close To, depending on the configuration) and that they are in this status for longer than configured number of days. If there are such work items the agent will compose a mail like this: &apos;Dear &lt;Send To&gt;. We have detected that the process &lt;name of the process&gt; have &lt;number of work items&gt; work items in Overdue for more than &lt;Days Ov [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OverdueAgentSettings_Readme_Prompt {
            get {
                return ResourceManager.GetString("OverdueAgentSettings.Readme.Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the receiver..
        /// </summary>
        internal static string OverdueAgentSettings_SendTo_Description {
            get {
                return ResourceManager.GetString("OverdueAgentSettings.SendTo.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 03 - E-Mail Settings.
        /// </summary>
        internal static string OverdueAgentSettings_SendTo_GroupName {
            get {
                return ResourceManager.GetString("OverdueAgentSettings.SendTo.GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send To.
        /// </summary>
        internal static string OverdueAgentSettings_SendTo_Name {
            get {
                return ResourceManager.GetString("OverdueAgentSettings.SendTo.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The E-mail address where the notification mail will be sent to..
        /// </summary>
        internal static string OverdueAgentSettings_SendToMail_Description {
            get {
                return ResourceManager.GetString("OverdueAgentSettings.SendToMail.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 03 - E-Mail Settings.
        /// </summary>
        internal static string OverdueAgentSettings_SendToMail_GroupName {
            get {
                return ResourceManager.GetString("OverdueAgentSettings.SendToMail.GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send To Address.
        /// </summary>
        internal static string OverdueAgentSettings_SendToMail_Name {
            get {
                return ResourceManager.GetString("OverdueAgentSettings.SendToMail.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration of the SMTP server to be used for sending notification e-mails..
        /// </summary>
        internal static string OverdueAgentSettings_ServerSettings_Description {
            get {
                return ResourceManager.GetString("OverdueAgentSettings.ServerSettings.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 03 - E-Mail Settings.
        /// </summary>
        internal static string OverdueAgentSettings_ServerSettings_GroupName {
            get {
                return ResourceManager.GetString("OverdueAgentSettings.ServerSettings.GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Server Settings.
        /// </summary>
        internal static string OverdueAgentSettings_ServerSettings_Name {
            get {
                return ResourceManager.GetString("OverdueAgentSettings.ServerSettings.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e mail address of the sender. If not set the UserName will be used.&quot;.
        /// </summary>
        internal static string SmtpSettings_From_Description {
            get {
                return ResourceManager.GetString("SmtpSettings.From.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from e-mail address.
        /// </summary>
        internal static string SmtpSettings_From_Name {
            get {
                return ResourceManager.GetString("SmtpSettings.From.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password for the user to authorize on SMTP server..
        /// </summary>
        internal static string SmtpSettings_Password_Description {
            get {
                return ResourceManager.GetString("SmtpSettings.Password.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SmtpSettings_Password_Name {
            get {
                return ResourceManager.GetString("SmtpSettings.Password.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address of the SMTP server..
        /// </summary>
        internal static string SmtpSettings_ServerAddress_Description {
            get {
                return ResourceManager.GetString("SmtpSettings.ServerAddress.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Address.
        /// </summary>
        internal static string SmtpSettings_ServerAddress_Name {
            get {
                return ResourceManager.GetString("SmtpSettings.ServerAddress.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The port of the SMTP server..
        /// </summary>
        internal static string SmtpSettings_ServerPort_Description {
            get {
                return ResourceManager.GetString("SmtpSettings.ServerPort.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Port.
        /// </summary>
        internal static string SmtpSettings_ServerPort_Name {
            get {
                return ResourceManager.GetString("SmtpSettings.ServerPort.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user for authorizing on SMTP server..
        /// </summary>
        internal static string SmtpSettings_UserName_Description {
            get {
                return ResourceManager.GetString("SmtpSettings.UserName.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string SmtpSettings_UserName_Name {
            get {
                return ResourceManager.GetString("SmtpSettings.UserName.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use SSL for establishing connection..
        /// </summary>
        internal static string SmtpSettings_UseSSL_Description {
            get {
                return ResourceManager.GetString("SmtpSettings.UseSSL.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use SSL.
        /// </summary>
        internal static string SmtpSettings_UseSSL_Name {
            get {
                return ResourceManager.GetString("SmtpSettings.UseSSL.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing and Filtering Settings.
        /// </summary>
        internal static string WatermarkSettings_Common_Name {
            get {
                return ResourceManager.GetString("WatermarkSettings.Common.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string WatermarkSettings_WatermarkText_Description {
            get {
                return ResourceManager.GetString("WatermarkSettings.WatermarkText.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watermark Text.
        /// </summary>
        internal static string WatermarkSettings_WatermarkText_Name {
            get {
                return ResourceManager.GetString("WatermarkSettings.WatermarkText.Name", resourceCulture);
            }
        }
    }
}
