//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivitySettings.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ActivitySettings.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON file sample.
        /// </summary>
        public static string ActivityConfiguration_CBDependencyDesc_Description {
            get {
                return ResourceManager.GetString("ActivityConfiguration_CBDependencyDesc_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Dependant settings.
        /// </summary>
        public static string ActivityConfiguration_CBDependencyDesc_GroupName {
            get {
                return ResourceManager.GetString("ActivityConfiguration_CBDependencyDesc_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency Description.
        /// </summary>
        public static string ActivityConfiguration_CBDependencyDesc_Name {
            get {
                return ResourceManager.GetString("ActivityConfiguration_CBDependencyDesc_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item dependent on a check box.
        /// </summary>
        public static string ActivityConfiguration_CBDependentItem_Description {
            get {
                return ResourceManager.GetString("ActivityConfiguration_CBDependentItem_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Dependant settings.
        /// </summary>
        public static string ActivityConfiguration_CBDependentItem_GroupName {
            get {
                return ResourceManager.GetString("ActivityConfiguration_CBDependentItem_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check box dependent item.
        /// </summary>
        public static string ActivityConfiguration_CBDependentItem_Name {
            get {
                return ResourceManager.GetString("ActivityConfiguration_CBDependentItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check box sample.
        /// </summary>
        public static string ActivityConfiguration_CheckBoxData_Description {
            get {
                return ResourceManager.GetString("ActivityConfiguration_CheckBoxData_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Dependant settings.
        /// </summary>
        public static string ActivityConfiguration_CheckBoxData_GroupName {
            get {
                return ResourceManager.GetString("ActivityConfiguration_CheckBoxData_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check box data.
        /// </summary>
        public static string ActivityConfiguration_CheckBoxData_Name {
            get {
                return ResourceManager.GetString("ActivityConfiguration_CheckBoxData_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database lookup settings.
        /// </summary>
        public static string ActivityConfiguration_DatabaseLookup_Description {
            get {
                return ResourceManager.GetString("ActivityConfiguration_DatabaseLookup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Database Lookups (Complex classes).
        /// </summary>
        public static string ActivityConfiguration_DatabaseLookup_GroupName {
            get {
                return ResourceManager.GetString("ActivityConfiguration_DatabaseLookup_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Lookup.
        /// </summary>
        public static string ActivityConfiguration_DatabaseLookup_Name {
            get {
                return ResourceManager.GetString("ActivityConfiguration_DatabaseLookup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON file sample.
        /// </summary>
        public static string ActivityConfiguration_DBLookupDesc_Description {
            get {
                return ResourceManager.GetString("ActivityConfiguration_DBLookupDesc_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Database Lookups (Complex classes).
        /// </summary>
        public static string ActivityConfiguration_DBLookupDesc_GroupName {
            get {
                return ResourceManager.GetString("ActivityConfiguration_DBLookupDesc_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Lookup Description.
        /// </summary>
        public static string ActivityConfiguration_DBLookupDesc_Name {
            get {
                return ResourceManager.GetString("ActivityConfiguration_DBLookupDesc_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stores the one of document types assigned to the process.
        /// </summary>
        public static string ActivityConfiguration_DocumentType_Description {
            get {
                return ResourceManager.GetString("ActivityConfiguration_DocumentType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform data.
        /// </summary>
        public static string ActivityConfiguration_DocumentType_GroupName {
            get {
                return ResourceManager.GetString("ActivityConfiguration_DocumentType_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type selector.
        /// </summary>
        public static string ActivityConfiguration_DocumentType_Name {
            get {
                return ResourceManager.GetString("ActivityConfiguration_DocumentType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stores the subset of the fields from the document type above.
        /// </summary>
        public static string ActivityConfiguration_IndexFields_Description {
            get {
                return ResourceManager.GetString("ActivityConfiguration_IndexFields_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform data.
        /// </summary>
        public static string ActivityConfiguration_IndexFields_GroupName {
            get {
                return ResourceManager.GetString("ActivityConfiguration_IndexFields_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected fields.
        /// </summary>
        public static string ActivityConfiguration_IndexFields_Name {
            get {
                return ResourceManager.GetString("ActivityConfiguration_IndexFields_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON file sample.
        /// </summary>
        public static string ActivityConfiguration_JSONSettings_Description {
            get {
                return ResourceManager.GetString("ActivityConfiguration_JSONSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Binary File.
        /// </summary>
        public static string ActivityConfiguration_JSONSettings_GroupName {
            get {
                return ResourceManager.GetString("ActivityConfiguration_JSONSettings_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON File.
        /// </summary>
        public static string ActivityConfiguration_JSONSettings_Name {
            get {
                return ResourceManager.GetString("ActivityConfiguration_JSONSettings_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON file sample.
        /// </summary>
        public static string ActivityConfiguration_JSONSettingsDesc_Description {
            get {
                return ResourceManager.GetString("ActivityConfiguration_JSONSettingsDesc_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Binary File.
        /// </summary>
        public static string ActivityConfiguration_JSONSettingsDesc_GroupName {
            get {
                return ResourceManager.GetString("ActivityConfiguration_JSONSettingsDesc_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON File Description.
        /// </summary>
        public static string ActivityConfiguration_JSONSettingsDesc_Name {
            get {
                return ResourceManager.GetString("ActivityConfiguration_JSONSettingsDesc_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item list dependent on a check box.
        /// </summary>
        public static string ActivityConfiguration_LstDependent_Description {
            get {
                return ResourceManager.GetString("ActivityConfiguration_LstDependent_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Dependant settings.
        /// </summary>
        public static string ActivityConfiguration_LstDependent_GroupName {
            get {
                return ResourceManager.GetString("ActivityConfiguration_LstDependent_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check box dependent list.
        /// </summary>
        public static string ActivityConfiguration_LstDependent_Name {
            get {
                return ResourceManager.GetString("ActivityConfiguration_LstDependent_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stores the one of available media types.
        /// </summary>
        public static string ActivityConfiguration_MediaType_Description {
            get {
                return ResourceManager.GetString("ActivityConfiguration_MediaType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform data.
        /// </summary>
        public static string ActivityConfiguration_MediaType_GroupName {
            get {
                return ResourceManager.GetString("ActivityConfiguration_MediaType_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Type selector.
        /// </summary>
        public static string ActivityConfiguration_MediaType_Name {
            get {
                return ResourceManager.GetString("ActivityConfiguration_MediaType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describes usage of the platform data.
        /// </summary>
        public static string ActivityConfiguration_PlatformDataDesc_Description {
            get {
                return ResourceManager.GetString("ActivityConfiguration_PlatformDataDesc_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform data.
        /// </summary>
        public static string ActivityConfiguration_PlatformDataDesc_GroupName {
            get {
                return ResourceManager.GetString("ActivityConfiguration_PlatformDataDesc_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform Data Description.
        /// </summary>
        public static string ActivityConfiguration_PlatformDataDesc_Name {
            get {
                return ResourceManager.GetString("ActivityConfiguration_PlatformDataDesc_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database name.
        /// </summary>
        public static string DatabaseConnection_DatabaseName_Name {
            get {
                return ResourceManager.GetString("DatabaseConnection_DatabaseName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is required..
        /// </summary>
        public static string DatabaseConnection_DatabaseName_RequiredAttribute_ErrorMessage {
            get {
                return ResourceManager.GetString("DatabaseConnection_DatabaseName_RequiredAttribute_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrated security.
        /// </summary>
        public static string DatabaseConnection_IntegratedSecurity_Name {
            get {
                return ResourceManager.GetString("DatabaseConnection_IntegratedSecurity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string DatabaseConnection_Password_Name {
            get {
                return ResourceManager.GetString("DatabaseConnection_Password_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name.
        /// </summary>
        public static string DatabaseConnection_ServerName_Name {
            get {
                return ResourceManager.GetString("DatabaseConnection_ServerName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is required..
        /// </summary>
        public static string DatabaseConnection_ServerName_RequiredAttribute_ErrorMessage {
            get {
                return ResourceManager.GetString("DatabaseConnection_ServerName_RequiredAttribute_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string DatabaseConnection_Username_Name {
            get {
                return ResourceManager.GetString("DatabaseConnection_Username_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns with column display name.
        /// </summary>
        public static string DatabaseLookup_Columns_Description {
            get {
                return ResourceManager.GetString("DatabaseLookup_Columns_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Columns.
        /// </summary>
        public static string DatabaseLookup_Columns_Name {
            get {
                return ResourceManager.GetString("DatabaseLookup_Columns_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connection settings.
        /// </summary>
        public static string DatabaseLookup_DatabaseConnection_Description {
            get {
                return ResourceManager.GetString("DatabaseLookup_DatabaseConnection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Connection.
        /// </summary>
        public static string DatabaseLookup_DatabaseConnection_Name {
            get {
                return ResourceManager.GetString("DatabaseLookup_DatabaseConnection_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns used in full text search delimited by comma.
        /// </summary>
        public static string DatabaseLookup_FullTextColumns_Description {
            get {
                return ResourceManager.GetString("DatabaseLookup_FullTextColumns_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full text search columns (comma-separated).
        /// </summary>
        public static string DatabaseLookup_FullTextColumns_Name {
            get {
                return ResourceManager.GetString("DatabaseLookup_FullTextColumns_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support for full text search.
        /// </summary>
        public static string DatabaseLookup_FullTextSearch_Description {
            get {
                return ResourceManager.GetString("DatabaseLookup_FullTextSearch_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow full text search.
        /// </summary>
        public static string DatabaseLookup_FullTextSearch_Name {
            get {
                return ResourceManager.GetString("DatabaseLookup_FullTextSearch_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of results returned.
        /// </summary>
        public static string DatabaseLookup_MaxResults_Description {
            get {
                return ResourceManager.GetString("DatabaseLookup_MaxResults_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max returned results.
        /// </summary>
        public static string DatabaseLookup_MaxResults_Name {
            get {
                return ResourceManager.GetString("DatabaseLookup_MaxResults_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup name.
        /// </summary>
        public static string DatabaseLookup_Name_Description {
            get {
                return ResourceManager.GetString("DatabaseLookup_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DatabaseLookup_Name_Name {
            get {
                return ResourceManager.GetString("DatabaseLookup_Name_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name.
        /// </summary>
        public static string DatabaseLookup_TableName_Description {
            get {
                return ResourceManager.GetString("DatabaseLookup_TableName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name.
        /// </summary>
        public static string DatabaseLookup_TableName_Name {
            get {
                return ResourceManager.GetString("DatabaseLookup_TableName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showcase that demonstrates how to assign fields to be used in the configuration.
        /// </summary>
        public static string ExternalSettings_AssignedFields_Description {
            get {
                return ResourceManager.GetString("ExternalSettings_AssignedFields_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Assigner.
        /// </summary>
        public static string ExternalSettings_AssignedFields_Name {
            get {
                return ResourceManager.GetString("ExternalSettings_AssignedFields_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fieldAssignment.
        /// </summary>
        public static string ExternalSettings_AssignedFields_Values_fieldAssignment {
            get {
                return ResourceManager.GetString("ExternalSettings_AssignedFields_Values_fieldAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property of type boolean.
        /// </summary>
        public static string ExternalSettings_BooleanProperty_Description {
            get {
                return ResourceManager.GetString("ExternalSettings_BooleanProperty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple properties.
        /// </summary>
        public static string ExternalSettings_BooleanProperty_GroupName {
            get {
                return ResourceManager.GetString("ExternalSettings_BooleanProperty_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean Property.
        /// </summary>
        public static string ExternalSettings_BooleanProperty_Name {
            get {
                return ResourceManager.GetString("ExternalSettings_BooleanProperty_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property of type color.
        /// </summary>
        public static string ExternalSettings_ColorProperty_Description {
            get {
                return ResourceManager.GetString("ExternalSettings_ColorProperty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple properties.
        /// </summary>
        public static string ExternalSettings_ColorProperty_GroupName {
            get {
                return ResourceManager.GetString("ExternalSettings_ColorProperty_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Property.
        /// </summary>
        public static string ExternalSettings_ColorProperty_Name {
            get {
                return ResourceManager.GetString("ExternalSettings_ColorProperty_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo box for comma delimited strings property.
        /// </summary>
        public static string ExternalSettings_CommaDelimitedCombo_Description {
            get {
                return ResourceManager.GetString("ExternalSettings_CommaDelimitedCombo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex properties.
        /// </summary>
        public static string ExternalSettings_CommaDelimitedCombo_GroupName {
            get {
                return ResourceManager.GetString("ExternalSettings_CommaDelimitedCombo_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo With comma delimited values.
        /// </summary>
        public static string ExternalSettings_CommaDelimitedCombo_Name {
            get {
                return ResourceManager.GetString("ExternalSettings_CommaDelimitedCombo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option A.
        /// </summary>
        public static string ExternalSettings_CommaDelimitedCombo_Values_Option_A {
            get {
                return ResourceManager.GetString("ExternalSettings_CommaDelimitedCombo_Values_Option A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option B.
        /// </summary>
        public static string ExternalSettings_CommaDelimitedCombo_Values_Option_B {
            get {
                return ResourceManager.GetString("ExternalSettings_CommaDelimitedCombo_Values_Option B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option C.
        /// </summary>
        public static string ExternalSettings_CommaDelimitedCombo_Values_Option_C {
            get {
                return ResourceManager.GetString("ExternalSettings_CommaDelimitedCombo_Values_Option C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property of type date time.
        /// </summary>
        public static string ExternalSettings_DateTimeProperty_Description {
            get {
                return ResourceManager.GetString("ExternalSettings_DateTimeProperty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple properties.
        /// </summary>
        public static string ExternalSettings_DateTimeProperty_GroupName {
            get {
                return ResourceManager.GetString("ExternalSettings_DateTimeProperty_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime Property.
        /// </summary>
        public static string ExternalSettings_DateTimeProperty_Name {
            get {
                return ResourceManager.GetString("ExternalSettings_DateTimeProperty_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop-down with document types assigned to the process.
        /// </summary>
        public static string ExternalSettings_DocumentTypeSelection_Description {
            get {
                return ResourceManager.GetString("ExternalSettings_DocumentTypeSelection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex properties.
        /// </summary>
        public static string ExternalSettings_DocumentTypeSelection_GroupName {
            get {
                return ResourceManager.GetString("ExternalSettings_DocumentTypeSelection_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available document types.
        /// </summary>
        public static string ExternalSettings_DocumentTypeSelection_Name {
            get {
                return ResourceManager.GetString("ExternalSettings_DocumentTypeSelection_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to document.
        /// </summary>
        public static string ExternalSettings_DocumentTypeSelection_Values_document {
            get {
                return ResourceManager.GetString("ExternalSettings_DocumentTypeSelection_Values_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showcase that demonstrate how to use a list as a property that accepts entering of valid numbers and usage of variables on list items..
        /// </summary>
        public static string ExternalSettings_DoubleMultiValueProperty_Description {
            get {
                return ResourceManager.GetString("ExternalSettings_DoubleMultiValueProperty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex properties.
        /// </summary>
        public static string ExternalSettings_DoubleMultiValueProperty_GroupName {
            get {
                return ResourceManager.GetString("ExternalSettings_DoubleMultiValueProperty_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Of Doubles.
        /// </summary>
        public static string ExternalSettings_DoubleMultiValueProperty_Name {
            get {
                return ResourceManager.GetString("ExternalSettings_DoubleMultiValueProperty_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property of type double.
        /// </summary>
        public static string ExternalSettings_DoubleProperty_Description {
            get {
                return ResourceManager.GetString("ExternalSettings_DoubleProperty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple properties.
        /// </summary>
        public static string ExternalSettings_DoubleProperty_GroupName {
            get {
                return ResourceManager.GetString("ExternalSettings_DoubleProperty_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Property.
        /// </summary>
        public static string ExternalSettings_DoubleProperty_Name {
            get {
                return ResourceManager.GetString("ExternalSettings_DoubleProperty_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo box for enumeration type property.
        /// </summary>
        public static string ExternalSettings_EnumPropertyCombo_Description {
            get {
                return ResourceManager.GetString("ExternalSettings_EnumPropertyCombo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex properties.
        /// </summary>
        public static string ExternalSettings_EnumPropertyCombo_GroupName {
            get {
                return ResourceManager.GetString("ExternalSettings_EnumPropertyCombo_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo With Enumerator.
        /// </summary>
        public static string ExternalSettings_EnumPropertyCombo_Name {
            get {
                return ResourceManager.GetString("ExternalSettings_EnumPropertyCombo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnumeratorValue1.
        /// </summary>
        public static string ExternalSettings_EnumPropertyCombo_Values_0 {
            get {
                return ResourceManager.GetString("ExternalSettings_EnumPropertyCombo_Values_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnumeratorValue2.
        /// </summary>
        public static string ExternalSettings_EnumPropertyCombo_Values_1 {
            get {
                return ResourceManager.GetString("ExternalSettings_EnumPropertyCombo_Values_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnumeratorValue3.
        /// </summary>
        public static string ExternalSettings_EnumPropertyCombo_Values_2 {
            get {
                return ResourceManager.GetString("ExternalSettings_EnumPropertyCombo_Values_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnumeratorValue4.
        /// </summary>
        public static string ExternalSettings_EnumPropertyCombo_Values_3 {
            get {
                return ResourceManager.GetString("ExternalSettings_EnumPropertyCombo_Values_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploader for string property.
        /// </summary>
        public static string ExternalSettings_FileUploadProperty_Description {
            get {
                return ResourceManager.GetString("ExternalSettings_FileUploadProperty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex properties.
        /// </summary>
        public static string ExternalSettings_FileUploadProperty_GroupName {
            get {
                return ResourceManager.GetString("ExternalSettings_FileUploadProperty_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Upload.
        /// </summary>
        public static string ExternalSettings_FileUploadProperty_Name {
            get {
                return ResourceManager.GetString("ExternalSettings_FileUploadProperty_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid for string dictionary property.
        /// </summary>
        public static string ExternalSettings_GridProperty_Description {
            get {
                return ResourceManager.GetString("ExternalSettings_GridProperty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex properties.
        /// </summary>
        public static string ExternalSettings_GridProperty_GroupName {
            get {
                return ResourceManager.GetString("ExternalSettings_GridProperty_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dummy Grid.
        /// </summary>
        public static string ExternalSettings_GridProperty_Name {
            get {
                return ResourceManager.GetString("ExternalSettings_GridProperty_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo box for integer dictionary property.
        /// </summary>
        public static string ExternalSettings_IntegerCombo_Description {
            get {
                return ResourceManager.GetString("ExternalSettings_IntegerCombo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex properties.
        /// </summary>
        public static string ExternalSettings_IntegerCombo_GroupName {
            get {
                return ResourceManager.GetString("ExternalSettings_IntegerCombo_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo With dictionary.
        /// </summary>
        public static string ExternalSettings_IntegerCombo_Name {
            get {
                return ResourceManager.GetString("ExternalSettings_IntegerCombo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One.
        /// </summary>
        public static string ExternalSettings_IntegerCombo_Values_1 {
            get {
                return ResourceManager.GetString("ExternalSettings_IntegerCombo_Values_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two.
        /// </summary>
        public static string ExternalSettings_IntegerCombo_Values_2 {
            get {
                return ResourceManager.GetString("ExternalSettings_IntegerCombo_Values_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three.
        /// </summary>
        public static string ExternalSettings_IntegerCombo_Values_3 {
            get {
                return ResourceManager.GetString("ExternalSettings_IntegerCombo_Values_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showcase that demonstrate how to use a list as a property that accepts entering integer numbers that are considered invalid if they are shorter than 2 digits. This sample also demonstrates that list entry type can be auto-detected Variable input on this property is disabled.
        /// </summary>
        public static string ExternalSettings_IntMultiValueProperty_Description {
            get {
                return ResourceManager.GetString("ExternalSettings_IntMultiValueProperty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex properties.
        /// </summary>
        public static string ExternalSettings_IntMultiValueProperty_GroupName {
            get {
                return ResourceManager.GetString("ExternalSettings_IntMultiValueProperty_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min length of list items must be 2 characters.
        /// </summary>
        public static string ExternalSettings_IntMultiValueProperty_MinLengthAttribute_ErrorMessage {
            get {
                return ResourceManager.GetString("ExternalSettings_IntMultiValueProperty_MinLengthAttribute_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of integers with min length.
        /// </summary>
        public static string ExternalSettings_IntMultiValueProperty_Name {
            get {
                return ResourceManager.GetString("ExternalSettings_IntMultiValueProperty_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property of type string with area input.
        /// </summary>
        public static string ExternalSettings_LongStringProperty_Description {
            get {
                return ResourceManager.GetString("ExternalSettings_LongStringProperty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple properties.
        /// </summary>
        public static string ExternalSettings_LongStringProperty_GroupName {
            get {
                return ResourceManager.GetString("ExternalSettings_LongStringProperty_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String Property (long).
        /// </summary>
        public static string ExternalSettings_LongStringProperty_Name {
            get {
                return ResourceManager.GetString("ExternalSettings_LongStringProperty_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop down with all media types available in the platform.
        /// </summary>
        public static string ExternalSettings_MediaTypeSelection_Description {
            get {
                return ResourceManager.GetString("ExternalSettings_MediaTypeSelection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex properties.
        /// </summary>
        public static string ExternalSettings_MediaTypeSelection_GroupName {
            get {
                return ResourceManager.GetString("ExternalSettings_MediaTypeSelection_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available media types.
        /// </summary>
        public static string ExternalSettings_MediaTypeSelection_Name {
            get {
                return ResourceManager.GetString("ExternalSettings_MediaTypeSelection_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to media.
        /// </summary>
        public static string ExternalSettings_MediaTypeSelection_Values_media {
            get {
                return ResourceManager.GetString("ExternalSettings_MediaTypeSelection_Values_media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nested class with file uploader as a property.
        /// </summary>
        public static string ExternalSettings_NestedClassProperty_Description {
            get {
                return ResourceManager.GetString("ExternalSettings_NestedClassProperty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nested Class.
        /// </summary>
        public static string ExternalSettings_NestedClassProperty_Name {
            get {
                return ResourceManager.GetString("ExternalSettings_NestedClassProperty_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property of type string with password characters.
        /// </summary>
        public static string ExternalSettings_PwdProperty_Description {
            get {
                return ResourceManager.GetString("ExternalSettings_PwdProperty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple properties.
        /// </summary>
        public static string ExternalSettings_PwdProperty_GroupName {
            get {
                return ResourceManager.GetString("ExternalSettings_PwdProperty_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Property.
        /// </summary>
        public static string ExternalSettings_PwdProperty_Name {
            get {
                return ResourceManager.GetString("ExternalSettings_PwdProperty_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showcase that demonstrates how to select a single field to be used in the configuration.
        /// </summary>
        public static string ExternalSettings_SelectedField_Description {
            get {
                return ResourceManager.GetString("ExternalSettings_SelectedField_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Field Selector.
        /// </summary>
        public static string ExternalSettings_SelectedField_Name {
            get {
                return ResourceManager.GetString("ExternalSettings_SelectedField_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to singleFieldSelection.
        /// </summary>
        public static string ExternalSettings_SelectedField_Values_singleFieldSelection {
            get {
                return ResourceManager.GetString("ExternalSettings_SelectedField_Values_singleFieldSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showcase that demonstrates how to select fields to be used in the configuration.
        /// </summary>
        public static string ExternalSettings_SelectedFields_Description {
            get {
                return ResourceManager.GetString("ExternalSettings_SelectedFields_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Field Selector.
        /// </summary>
        public static string ExternalSettings_SelectedFields_Name {
            get {
                return ResourceManager.GetString("ExternalSettings_SelectedFields_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to multiFieldSelection.
        /// </summary>
        public static string ExternalSettings_SelectedFields_Values_multiFieldSelection {
            get {
                return ResourceManager.GetString("ExternalSettings_SelectedFields_Values_multiFieldSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showcase that demonstrate how to use a list as a property that accepts entering of e-mails. Variable input on this property is disabled.
        /// </summary>
        public static string ExternalSettings_StringMultiValueProperty_Description {
            get {
                return ResourceManager.GetString("ExternalSettings_StringMultiValueProperty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex properties.
        /// </summary>
        public static string ExternalSettings_StringMultiValueProperty_GroupName {
            get {
                return ResourceManager.GetString("ExternalSettings_StringMultiValueProperty_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Of Emails.
        /// </summary>
        public static string ExternalSettings_StringMultiValueProperty_Name {
            get {
                return ResourceManager.GetString("ExternalSettings_StringMultiValueProperty_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property of type string.
        /// </summary>
        public static string ExternalSettings_StringProperty_Description {
            get {
                return ResourceManager.GetString("ExternalSettings_StringProperty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple properties.
        /// </summary>
        public static string ExternalSettings_StringProperty_GroupName {
            get {
                return ResourceManager.GetString("ExternalSettings_StringProperty_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String Property.
        /// </summary>
        public static string ExternalSettings_StringProperty_Name {
            get {
                return ResourceManager.GetString("ExternalSettings_StringProperty_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showcase that demonstrates how to select single field to be used in the configuration.
        /// </summary>
        public static string NestedWithFiles_SelectedField_Description {
            get {
                return ResourceManager.GetString("NestedWithFiles_SelectedField_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Field Selector.
        /// </summary>
        public static string NestedWithFiles_SelectedField_Name {
            get {
                return ResourceManager.GetString("NestedWithFiles_SelectedField_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File upload with File Object property that allows setting of the variables.
        /// </summary>
        public static string NestedWithFiles_UploadedFile_Description {
            get {
                return ResourceManager.GetString("NestedWithFiles_UploadedFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Upload with object.
        /// </summary>
        public static string NestedWithFiles_UploadedFile_Name {
            get {
                return ResourceManager.GetString("NestedWithFiles_UploadedFile_Name", resourceCulture);
            }
        }
    }
}
